In [1]:
import GEOparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pylab as pl
import seaborn as sns
import pyreadr

In [2]:
gse_data = pd.read_csv('GSE72267_series_matrix.txt', sep='\t',  comment='!')

In [3]:
gse_data

,ID_REF,GSM1859079,GSM1859080,GSM1859081,GSM1859082,GSM1859083,GSM1859084,GSM1859085,GSM1859086,GSM1859087,...,GSM1859128,GSM1859129,GSM1859130,GSM1859131,GSM1859132,GSM1859133,GSM1859134,GSM1859135,GSM1859136,GSM1859137
0,1007_s_at,7.349298,7.274405,6.719570,7.083267,7.452170,7.072315,7.051066,6.915191,6.724721,...,7.220690,7.273062,6.348098,7.215291,7.158651,6.939362,6.953196,6.783862,7.508211,7.442646
1,1053_at,8.906082,8.997323,9.145367,8.947209,8.679888,9.021920,8.833503,8.996459,8.499686,...,9.114221,8.149797,9.125882,8.945029,9.098237,8.231308,8.962738,8.335829,8.669423,9.209691
2,117_at,10.916643,11.173430,11.369026,11.274212,10.783615,11.126310,10.577591,11.064433,10.878215,...,11.873479,11.157583,11.803321,11.393424,11.568479,11.679601,11.522308,11.012502,11.605217,12.168853
3,121_at,6.954244,6.334305,6.733312,7.096500,6.813166,6.610517,6.888822,6.995565,6.561855,...,6.646920,6.713738,7.034526,6.822774,6.696431,6.798336,6.599626,6.271728,5.885947,6.800522
4,1255_g_at,2.702785,2.581031,2.469741,2.774409,2.642078,2.732572,2.646264,3.032687,2.642967,...,2.782319,2.540955,2.672644,2.703629,2.577448,2.678776,2.649259,2.667041,2.651123,2.543898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22272,AFFX-ThrX-5_at,3.086941,3.395082,3.211710,3.177194,3.240693,3.428652,3.414479,3.639821,3.213977,...,3.291512,3.084009,3.300177,3.388613,3.267444,3.089564,3.082268,3.087934,3.056692,3.401986
22273,AFFX-ThrX-M_at,3.073432,3.257221,3.403392,3.409128,3.037217,3.126156,3.325499,3.309700,3.181855,...,3.364188,3.175478,3.262015,3.099387,3.411084,3.338604,3.289487,3.344057,3.080960,3.040670
22274,AFFX-TrpnX-3_at,2.467247,2.692106,2.633840,2.517776,2.546762,2.815358,2.608742,3.069019,2.621296,...,2.775582,2.702807,2.518298,2.778495,2.682865,2.666095,2.819289,2.741852,2.770820,2.730419
22275,AFFX-TrpnX-5_at,3.531346,3.475607,3.624394,3.510254,3.376297,3.778116,3.334487,3.659660,3.388264,...,3.582253,3.554952,3.515270,3.853754,3.298534,3.684110,3.390299,3.412506,3.631528,3.421109
22276,AFFX-TrpnX-M_at,3.263501,3.483224,3.615799,3.652824,3.314186,3.576931,3.402869,3.549621,3.556317,...,3.553148,3.416231,3.344775,3.499232,3.375261,3.649036,3.608566,3.429875,3.409603,3.561035

In [4]:
# comment='#' 表示以 # 开头的行是注释行，需要跳过 
gpl_df = pd.read_csv('GPL571-17391.txt', sep='\t', comment='#')

In [5]:
gpl_df

,ID,GB_ACC,SPOT_ID,Species Scientific Name,Annotation Date,Sequence Type,Sequence Source,Target Description,Representative Public ID,Gene Title,Gene Symbol,ENTREZ_GENE_ID,RefSeq Transcript ID,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function
0,1007_s_at,U48705,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,U48705 /FEATURE=mRNA /DEFINITION=HSU48705 Huma...,U48705,discoidin domain receptor tyrosine kinase 1 //...,DDR1 /// MIR4640,780 /// 100616237,NM_001202521 /// NM_001202522 /// NM_001202523...,0001558 // regulation of cell growth // inferr...,0005576 // extracellular region // inferred fr...,0000166 // nucleotide binding // inferred from...
1,1053_at,M87338,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,M87338 /FEATURE= /DEFINITION=HUMA1SBU Human re...,M87338,"replication factor C (activator 1) 2, 40kDa",RFC2,5982,NM_001278791 /// NM_001278792 /// NM_001278793...,0000278 // mitotic cell cycle // traceable aut...,0005634 // nucleus // inferred from electronic...,0000166 // nucleotide binding // inferred from...
2,117_at,X51757,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,X51757 /FEATURE=cds /DEFINITION=HSP70B Human h...,X51757,heat shock 70kDa protein 6 (HSP70B'),HSPA6,3310,NM_002155,0000902 // cell morphogenesis // inferred from...,0005737 // cytoplasm // inferred from direct a...,0000166 // nucleotide binding // inferred from...
3,121_at,X69699,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,GenBank,X69699 /FEATURE= /DEFINITION=HSPAX8A H.sapiens...,X69699,paired box 8,PAX8,7849,NM_003466 /// NM_013951 /// NM_013952 /// NM_0...,0001655 // urogenital system development // in...,0005634 // nucleus // inferred from direct ass...,0000979 // RNA polymerase II core promoter seq...
4,1255_g_at,L36861,NaN,Homo sapiens,"Oct 6, 2014",Exemplar sequence,Affymetrix Proprietary Database,L36861 /FEATURE=expanded_cds /DEFINITION=HUMGC...,L36861,guanylate cyclase activator 1A (retina),GUCA1A,2978,NM_000409 /// XM_006715073,0007165 // signal transduction // non-traceabl...,0001750 // photoreceptor outer segment // infe...,0005509 // calcium ion binding // inferred fro...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22272,AFFX-ThrX-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,B. subtilis /GEN=thrC /DB_XREF=gb:X04603.1 /NO...,AFFX-ThrX-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22273,AFFX-ThrX-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=thrC, thrB /DB_XREF=gb:X04603...",AFFX-ThrX-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22274,AFFX-TrpnX-3_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpC, trpF /DB_XREF=gb:K01391...",AFFX-TrpnX-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22275,AFFX-TrpnX-5_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpE, trpD /DB_XREF=gb:K01391...",AFFX-TrpnX-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22276,AFFX-TrpnX-M_at,NaN,--Control,Homo sapiens,"Oct 6, 2014",Control sequence,Affymetrix Proprietary Database,"B. subtilis /GEN=trpD, trpC /DB_XREF=gb:K01391...",AFFX-TrpnX-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import pandas as pd

# 假设你已经将文件加载到 DataFrame 中，命名为 gpl_df
# gpl_df = pd.read_csv('your_file.csv')  # 如果是 CSV 文件
# gpl_df = pd.read_excel('your_file.xlsx')  # 如果是 Excel 文件

# 输出第一行的列名
print(gpl_df.columns.tolist())

['ID', 'GB_ACC', 'SPOT_ID', 'Species Scientific Name', 'Annotation Date', 'Sequence Type', 'Sequence Source', 'Target Description', 'Representative Public ID', 'Gene Title', 'Gene Symbol', 'ENTREZ_GENE_ID', 'RefSeq Transcript ID', 'Gene Ontology Biological Process', 'Gene Ontology Cellular Component', 'Gene Ontology Molecular Function']

In [7]:
# 2. 使用 pandas 的 merge 函数进行合并
merged_data = pd.merge(gse_data,gpl_df , left_on='ID_REF', right_on='ID', how='left')

In [8]:
merged_data

,ID_REF,GSM1859079,GSM1859080,GSM1859081,GSM1859082,GSM1859083,GSM1859084,GSM1859085,GSM1859086,GSM1859087,...,Sequence Source,Target Description,Representative Public ID,Gene Title,Gene Symbol,ENTREZ_GENE_ID,RefSeq Transcript ID,Gene Ontology Biological Process,Gene Ontology Cellular Component,Gene Ontology Molecular Function
0,1007_s_at,7.349298,7.274405,6.719570,7.083267,7.452170,7.072315,7.051066,6.915191,6.724721,...,Affymetrix Proprietary Database,U48705 /FEATURE=mRNA /DEFINITION=HSU48705 Huma...,U48705,discoidin domain receptor tyrosine kinase 1 //...,DDR1 /// MIR4640,780 /// 100616237,NM_001202521 /// NM_001202522 /// NM_001202523...,0001558 // regulation of cell growth // inferr...,0005576 // extracellular region // inferred fr...,0000166 // nucleotide binding // inferred from...
1,1053_at,8.906082,8.997323,9.145367,8.947209,8.679888,9.021920,8.833503,8.996459,8.499686,...,GenBank,M87338 /FEATURE= /DEFINITION=HUMA1SBU Human re...,M87338,"replication factor C (activator 1) 2, 40kDa",RFC2,5982,NM_001278791 /// NM_001278792 /// NM_001278793...,0000278 // mitotic cell cycle // traceable aut...,0005634 // nucleus // inferred from electronic...,0000166 // nucleotide binding // inferred from...
2,117_at,10.916643,11.173430,11.369026,11.274212,10.783615,11.126310,10.577591,11.064433,10.878215,...,Affymetrix Proprietary Database,X51757 /FEATURE=cds /DEFINITION=HSP70B Human h...,X51757,heat shock 70kDa protein 6 (HSP70B'),HSPA6,3310,NM_002155,0000902 // cell morphogenesis // inferred from...,0005737 // cytoplasm // inferred from direct a...,0000166 // nucleotide binding // inferred from...
3,121_at,6.954244,6.334305,6.733312,7.096500,6.813166,6.610517,6.888822,6.995565,6.561855,...,GenBank,X69699 /FEATURE= /DEFINITION=HSPAX8A H.sapiens...,X69699,paired box 8,PAX8,7849,NM_003466 /// NM_013951 /// NM_013952 /// NM_0...,0001655 // urogenital system development // in...,0005634 // nucleus // inferred from direct ass...,0000979 // RNA polymerase II core promoter seq...
4,1255_g_at,2.702785,2.581031,2.469741,2.774409,2.642078,2.732572,2.646264,3.032687,2.642967,...,Affymetrix Proprietary Database,L36861 /FEATURE=expanded_cds /DEFINITION=HUMGC...,L36861,guanylate cyclase activator 1A (retina),GUCA1A,2978,NM_000409 /// XM_006715073,0007165 // signal transduction // non-traceabl...,0001750 // photoreceptor outer segment // infe...,0005509 // calcium ion binding // inferred fro...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22272,AFFX-ThrX-5_at,3.086941,3.395082,3.211710,3.177194,3.240693,3.428652,3.414479,3.639821,3.213977,...,Affymetrix Proprietary Database,B. subtilis /GEN=thrC /DB_XREF=gb:X04603.1 /NO...,AFFX-ThrX-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22273,AFFX-ThrX-M_at,3.073432,3.257221,3.403392,3.409128,3.037217,3.126156,3.325499,3.309700,3.181855,...,Affymetrix Proprietary Database,"B. subtilis /GEN=thrC, thrB /DB_XREF=gb:X04603...",AFFX-ThrX-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22274,AFFX-TrpnX-3_at,2.467247,2.692106,2.633840,2.517776,2.546762,2.815358,2.608742,3.069019,2.621296,...,Affymetrix Proprietary Database,"B. subtilis /GEN=trpC, trpF /DB_XREF=gb:K01391...",AFFX-TrpnX-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22275,AFFX-TrpnX-5_at,3.531346,3.475607,3.624394,3.510254,3.376297,3.778116,3.334487,3.659660,3.388264,...,Affymetrix Proprietary Database,"B. subtilis /GEN=trpE, trpD /DB_XREF=gb:K01391...",AFFX-TrpnX-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22276,AFFX-TrpnX-M_at,3.263501,3.483224,3.615799,3.652824,3.314186,3.576931,3.402869,3.549621,3.556317,...,Affymetrix Proprietary Database,"B. subtilis /GEN=trpD, trpC /DB_XREF=gb:K01391...",AFFX-TrpnX-M,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
print(merged_data.columns.tolist())

['ID_REF', 'GSM1859079', 'GSM1859080', 'GSM1859081', 'GSM1859082', 'GSM1859083', 'GSM1859084', 'GSM1859085', 'GSM1859086', 'GSM1859087', 'GSM1859088', 'GSM1859089', 'GSM1859090', 'GSM1859091', 'GSM1859092', 'GSM1859093', 'GSM1859094', 'GSM1859095', 'GSM1859096', 'GSM1859097', 'GSM1859098', 'GSM1859099', 'GSM1859100', 'GSM1859101', 'GSM1859102', 'GSM1859103', 'GSM1859104', 'GSM1859105', 'GSM1859106', 'GSM1859107', 'GSM1859108', 'GSM1859109', 'GSM1859110', 'GSM1859111', 'GSM1859112', 'GSM1859113', 'GSM1859114', 'GSM1859115', 'GSM1859116', 'GSM1859117', 'GSM1859118', 'GSM1859119', 'GSM1859120', 'GSM1859121', 'GSM1859122', 'GSM1859123', 'GSM1859124', 'GSM1859125', 'GSM1859126', 'GSM1859127', 'GSM1859128', 'GSM1859129', 'GSM1859130', 'GSM1859131', 'GSM1859132', 'GSM1859133', 'GSM1859134', 'GSM1859135', 'GSM1859136', 'GSM1859137', 'ID', 'GB_ACC', 'SPOT_ID', 'Species Scientific Name', 'Annotation Date', 'Sequence Type', 'Sequence Source', 'Target Description', 'Representative Public ID', 'Gene Title', 'Gene Symbol', 'ENTREZ_GENE_ID', 'RefSeq Transcript ID', 'Gene Ontology Biological Process', 'Gene Ontology Cellular Component', 'Gene Ontology Molecular Function']

In [12]:
# 删除指定的列
columns_to_drop =['ID_REF','ID', 'GB_ACC', 'SPOT_ID', 'Species Scientific Name', 'Annotation Date', 'Sequence Type', 'Sequence Source', 'Target Description', 'Representative Public ID', 'Gene Title',  'ENTREZ_GENE_ID', 'RefSeq Transcript ID', 'Gene Ontology Biological Process', 'Gene Ontology Cellular Component', 'Gene Ontology Molecular Function']
df = merged_data.drop(columns=columns_to_drop)

In [13]:
df

,GSM1859079,GSM1859080,GSM1859081,GSM1859082,GSM1859083,GSM1859084,GSM1859085,GSM1859086,GSM1859087,GSM1859088,...,GSM1859129,GSM1859130,GSM1859131,GSM1859132,GSM1859133,GSM1859134,GSM1859135,GSM1859136,GSM1859137,Gene Symbol
0,7.349298,7.274405,6.719570,7.083267,7.452170,7.072315,7.051066,6.915191,6.724721,6.752708,...,7.273062,6.348098,7.215291,7.158651,6.939362,6.953196,6.783862,7.508211,7.442646,DDR1 /// MIR4640
1,8.906082,8.997323,9.145367,8.947209,8.679888,9.021920,8.833503,8.996459,8.499686,9.113918,...,8.149797,9.125882,8.945029,9.098237,8.231308,8.962738,8.335829,8.669423,9.209691,RFC2
2,10.916643,11.173430,11.369026,11.274212,10.783615,11.126310,10.577591,11.064433,10.878215,11.542708,...,11.157583,11.803321,11.393424,11.568479,11.679601,11.522308,11.012502,11.605217,12.168853,HSPA6
3,6.954244,6.334305,6.733312,7.096500,6.813166,6.610517,6.888822,6.995565,6.561855,7.064596,...,6.713738,7.034526,6.822774,6.696431,6.798336,6.599626,6.271728,5.885947,6.800522,PAX8
4,2.702785,2.581031,2.469741,2.774409,2.642078,2.732572,2.646264,3.032687,2.642967,2.429493,...,2.540955,2.672644,2.703629,2.577448,2.678776,2.649259,2.667041,2.651123,2.543898,GUCA1A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22272,3.086941,3.395082,3.211710,3.177194,3.240693,3.428652,3.414479,3.639821,3.213977,3.305505,...,3.084009,3.300177,3.388613,3.267444,3.089564,3.082268,3.087934,3.056692,3.401986,NaN
22273,3.073432,3.257221,3.403392,3.409128,3.037217,3.126156,3.325499,3.309700,3.181855,3.349635,...,3.175478,3.262015,3.099387,3.411084,3.338604,3.289487,3.344057,3.080960,3.040670,NaN
22274,2.467247,2.692106,2.633840,2.517776,2.546762,2.815358,2.608742,3.069019,2.621296,2.454931,...,2.702807,2.518298,2.778495,2.682865,2.666095,2.819289,2.741852,2.770820,2.730419,NaN
22275,3.531346,3.475607,3.624394,3.510254,3.376297,3.778116,3.334487,3.659660,3.388264,3.331126,...,3.554952,3.515270,3.853754,3.298534,3.684110,3.390299,3.412506,3.631528,3.421109,NaN
22276,3.263501,3.483224,3.615799,3.652824,3.314186,3.576931,3.402869,3.549621,3.556317,3.263020,...,3.416231,3.344775,3.499232,3.375261,3.649036,3.608566,3.429875,3.409603,3.561035,NaN

In [15]:
# 4. 将 symbol 列移到最前面
cols = ['Gene Symbol'] + [col for col in df if col != 'Gene Symbol']
merged_data = df[cols]

In [ ]:
merged_data

In [16]:
# 删除 symbol 列为 NaN 的行
merged_data = merged_data.dropna(subset=['Gene Symbol'])

In [17]:
merged_data

,Gene Symbol,GSM1859079,GSM1859080,GSM1859081,GSM1859082,GSM1859083,GSM1859084,GSM1859085,GSM1859086,GSM1859087,...,GSM1859128,GSM1859129,GSM1859130,GSM1859131,GSM1859132,GSM1859133,GSM1859134,GSM1859135,GSM1859136,GSM1859137
0,DDR1 /// MIR4640,7.349298,7.274405,6.719570,7.083267,7.452170,7.072315,7.051066,6.915191,6.724721,...,7.220690,7.273062,6.348098,7.215291,7.158651,6.939362,6.953196,6.783862,7.508211,7.442646
1,RFC2,8.906082,8.997323,9.145367,8.947209,8.679888,9.021920,8.833503,8.996459,8.499686,...,9.114221,8.149797,9.125882,8.945029,9.098237,8.231308,8.962738,8.335829,8.669423,9.209691
2,HSPA6,10.916643,11.173430,11.369026,11.274212,10.783615,11.126310,10.577591,11.064433,10.878215,...,11.873479,11.157583,11.803321,11.393424,11.568479,11.679601,11.522308,11.012502,11.605217,12.168853
3,PAX8,6.954244,6.334305,6.733312,7.096500,6.813166,6.610517,6.888822,6.995565,6.561855,...,6.646920,6.713738,7.034526,6.822774,6.696431,6.798336,6.599626,6.271728,5.885947,6.800522
4,GUCA1A,2.702785,2.581031,2.469741,2.774409,2.642078,2.732572,2.646264,3.032687,2.642967,...,2.782319,2.540955,2.672644,2.703629,2.577448,2.678776,2.649259,2.667041,2.651123,2.543898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22233,GAPDH,12.925947,12.947041,12.720696,12.923090,12.289434,13.272422,12.630564,12.749484,12.737896,...,13.313082,13.080694,13.350504,13.192283,13.104286,13.247783,13.210995,13.172013,13.017133,13.404501
22234,STAT1,11.609677,11.375651,11.225133,11.957166,11.923471,11.655967,11.957050,11.266292,11.803676,...,11.774936,11.484791,11.536012,11.425437,11.360102,11.566625,11.111058,11.532416,11.827014,11.013149
22235,STAT1,11.292739,10.888640,10.413351,11.584847,11.096845,11.839026,11.404928,10.946619,11.251119,...,11.867404,11.427891,11.644824,11.147897,10.672025,11.482376,10.955276,11.206111,11.225752,11.039593
22236,STAT1,8.800638,8.972416,8.655510,9.690922,8.774921,9.996378,8.944836,8.548092,9.131166,...,10.079041,9.124021,9.834603,8.919372,7.788655,9.499253,8.644291,9.039861,9.631993,9.040594
22237,STAT1,9.802274,9.681963,8.925059,10.458847,10.090033,9.824921,10.328368,8.808294,10.143828,...,10.561362,9.693870,10.295716,9.789957,8.768604,9.892291,9.010531,9.631941,10.107366,8.860658

In [18]:
# 计算每个探针的表达值平均值
merged_data['mean_expression'] = merged_data.filter(regex='^GSM').mean(axis=1)

# 根据 symbol 和 mean_expression 对数据进行排序, 同一个 symbol 中 mean_expression 最大的排在前面
merged_data = merged_data.sort_values(['Gene Symbol', 'mean_expression'], ascending=[True, False])

# 根据 symbol 去重，保留 mean_expression 最大的
merged_data = merged_data.drop_duplicates(subset='Gene Symbol', keep='first')

# 删除 mean_expression 列
merged_data = merged_data.drop('mean_expression', axis=1)

In [19]:
merged_data

,Gene Symbol,GSM1859079,GSM1859080,GSM1859081,GSM1859082,GSM1859083,GSM1859084,GSM1859085,GSM1859086,GSM1859087,...,GSM1859128,GSM1859129,GSM1859130,GSM1859131,GSM1859132,GSM1859133,GSM1859134,GSM1859135,GSM1859136,GSM1859137
20314,A1CF,3.740457,3.589668,4.001616,3.922480,3.825041,3.727894,3.174143,3.900209,3.412826,...,3.358709,3.778956,3.231725,3.588181,3.640964,3.442662,3.343009,3.355641,3.707557,3.592485
17121,A2M,6.188210,6.343766,5.564382,5.831597,6.409660,5.616699,5.713348,5.742100,5.946202,...,5.898099,6.337732,5.801519,6.434766,5.866802,6.249231,6.492982,6.058761,5.734053,5.279530
18851,A4GALT,6.123470,6.377847,6.764953,6.561627,6.392594,6.841788,6.306452,6.616951,6.509077,...,6.593544,6.269886,6.954067,6.669650,6.569091,6.481816,6.565538,6.449813,6.376380,6.405363
20493,A4GNT,2.933598,2.677448,3.334061,2.927740,2.773846,2.694206,2.758840,3.322035,2.864345,...,2.811331,3.022493,2.543672,3.060173,2.749411,2.955675,2.910911,2.952688,2.926041,2.762812
17439,AAAS,8.492358,8.736388,8.184672,8.245925,8.183062,9.266868,8.387620,8.248685,8.035643,...,8.922656,8.673856,8.809357,8.841401,8.915220,8.532027,8.833844,8.765720,8.671514,8.888536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18002,ZXDC,9.811959,10.207077,10.510775,9.933101,9.781409,9.572830,9.551447,10.012790,9.498197,...,10.104047,9.688590,9.946599,9.993261,9.718882,9.772788,10.042210,9.723835,9.961672,10.123696
15078,ZYX,10.884844,11.209250,11.603966,10.659977,10.504985,11.022255,10.453795,11.363431,10.386790,...,11.637016,11.074116,11.733548,10.988772,10.754228,11.370479,11.194459,10.899846,10.395507,11.242259
11985,ZZEF1,10.057091,10.325466,10.288874,10.377403,9.961986,9.979125,10.024469,10.169654,10.124011,...,10.051758,9.554702,10.475801,10.099771,9.329204,10.044489,10.392365,10.000310,9.745671,10.144231
12277,ZZZ3,7.832567,7.821914,7.350538,7.221889,8.536433,6.984086,8.305796,6.947127,8.082162,...,7.595748,8.420111,7.124782,7.690041,8.583961,8.012075,7.546207,8.516217,8.638789,7.286510
14152,abParts /// IGKC /// IGKV4-1 /// IGKV4-1,7.993011,8.764162,9.369258,7.735125,8.113535,8.965268,8.503500,8.813005,9.934119,...,7.778551,9.219603,8.672278,7.978830,7.100286,9.533244,8.131726,8.697053,9.068979,8.511413

In [20]:
df = merged_data.set_index(["Gene Symbol"])

In [21]:
df

,GSM1859079,GSM1859080,GSM1859081,GSM1859082,GSM1859083,GSM1859084,GSM1859085,GSM1859086,GSM1859087,GSM1859088,...,GSM1859128,GSM1859129,GSM1859130,GSM1859131,GSM1859132,GSM1859133,GSM1859134,GSM1859135,GSM1859136,GSM1859137
Gene Symbol,,,,,,,,,,,,,,,,,,,,,
A1CF,3.740457,3.589668,4.001616,3.922480,3.825041,3.727894,3.174143,3.900209,3.412826,3.687393,...,3.358709,3.778956,3.231725,3.588181,3.640964,3.442662,3.343009,3.355641,3.707557,3.592485
A2M,6.188210,6.343766,5.564382,5.831597,6.409660,5.616699,5.713348,5.742100,5.946202,5.838446,...,5.898099,6.337732,5.801519,6.434766,5.866802,6.249231,6.492982,6.058761,5.734053,5.279530
A4GALT,6.123470,6.377847,6.764953,6.561627,6.392594,6.841788,6.306452,6.616951,6.509077,6.435258,...,6.593544,6.269886,6.954067,6.669650,6.569091,6.481816,6.565538,6.449813,6.376380,6.405363
A4GNT,2.933598,2.677448,3.334061,2.927740,2.773846,2.694206,2.758840,3.322035,2.864345,2.670564,...,2.811331,3.022493,2.543672,3.060173,2.749411,2.955675,2.910911,2.952688,2.926041,2.762812
AAAS,8.492358,8.736388,8.184672,8.245925,8.183062,9.266868,8.387620,8.248685,8.035643,8.366766,...,8.922656,8.673856,8.809357,8.841401,8.915220,8.532027,8.833844,8.765720,8.671514,8.888536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZXDC,9.811959,10.207077,10.510775,9.933101,9.781409,9.572830,9.551447,10.012790,9.498197,10.170742,...,10.104047,9.688590,9.946599,9.993261,9.718882,9.772788,10.042210,9.723835,9.961672,10.123696
ZYX,10.884844,11.209250,11.603966,10.659977,10.504985,11.022255,10.453795,11.363431,10.386790,10.956104,...,11.637016,11.074116,11.733548,10.988772,10.754228,11.370479,11.194459,10.899846,10.395507,11.242259
ZZEF1,10.057091,10.325466,10.288874,10.377403,9.961986,9.979125,10.024469,10.169654,10.124011,10.271622,...,10.051758,9.554702,10.475801,10.099771,9.329204,10.044489,10.392365,10.000310,9.745671,10.144231
ZZZ3,7.832567,7.821914,7.350538,7.221889,8.536433,6.984086,8.305796,6.947127,8.082162,7.657137,...,7.595748,8.420111,7.124782,7.690041,8.583961,8.012075,7.546207,8.516217,8.638789,7.286510
abParts /// IGKC /// IGKV4-1 /// IGKV4-1,7.993011,8.764162,9.369258,7.735125,8.113535,8.965268,8.503500,8.813005,9.934119,9.537974,...,7.778551,9.219603,8.672278,7.978830,7.100286,9.533244,8.131726,8.697053,9.068979,8.511413

In [22]:
df.to_csv("VV.csv")

In [13]:
# 定义新的列顺序
new_order = [
    'GSM569830', 'GSM569832', 'GSM569833', 'GSM569835', 'GSM569836', 
    'GSM569837', 'GSM569838', 'GSM569839', 'GSM569840', 'GSM569841', 'GSM569842', 
    'GSM569844', 'GSM569845', 'GSM569846', 'GSM569847', 'GSM569831', 'GSM569834', 
    'GSM569843', 'GSM569848', 'GSM569849', 'GSM569850', 'GSM569851', 'GSM569852'
]

# 调整列顺序
df = df[new_order]

# 显示调整后的DataFrame
df

KeyError: "None of [Index(['GSM569830', 'GSM569832', 'GSM569833', 'GSM569835', 'GSM569836',\n       'GSM569837', 'GSM569838', 'GSM569839', 'GSM569840', 'GSM569841',\n       'GSM569842', 'GSM569844', 'GSM569845', 'GSM569846', 'GSM569847',\n       'GSM569831', 'GSM569834', 'GSM569843', 'GSM569848', 'GSM569849',\n       'GSM569850', 'GSM569851', 'GSM569852'],\n      dtype='object')] are in the [columns]"

In [23]:
df.to_csv("VV.csv")